package com.kevinquan.cwa.model.levels;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Hashtable;
import java.util.List;

import com.kevinquan.cwa.model.Card;
import com.kevinquan.cwa.model.buildings.CornDome;
import com.kevinquan.cwa.model.buildings.CornParthenon;
import com.kevinquan.cwa.model.buildings.SchoolHouse;
import com.kevinquan.cwa.model.creatures.corn.Cornball;
import com.kevinquan.cwa.model.creatures.corn.EthanAllfire;
import com.kevinquan.cwa.model.creatures.corn.HuskerWorm;
import com.kevinquan.cwa.model.creatures.nice.AngelHeart;
import com.kevinquan.cwa.model.creatures.nice.FatGoat;
import com.kevinquan.cwa.model.creatures.nice.Fluffapillar;
import com.kevinquan.cwa.model.creatures.nice.GoldAngelHeart;
import com.kevinquan.cwa.model.creatures.nice.GoldFatGoat;
import com.kevinquan.cwa.model.creatures.nice.SoftEyeling;
import com.kevinquan.cwa.model.creatures.plains.CoolDog;
import com.kevinquan.cwa.model.creatures.plains.GrapeSlimey;
import com.kevinquan.cwa.model.creatures.plains.HeavenlyGazer;
import com.kevinquan.cwa.model.creatures.rainbow.Mouthball;
import com.kevinquan.cwa.model.creatures.rainbow.ThePig;
import com.kevinquan.cwa.model.creatures.rainbow.WhiteNinja;
import com.kevinquan.cwa.model.creatures.sandy.BeachMum;
import com.kevinquan.cwa.model.creatures.sandy.BurningHand;
import com.kevinquan.cwa.model.creatures.sandy.GreenCactaball;
import com.kevinquan.cwa.model.creatures.sandy.MsMummy;
import com.kevinquan.cwa.model.creatures.swamp.OrangeSlimey;
import com.kevinquan.cwa.model.creatures.swamp.TeethLeaf;
import com.kevinquan.cwa.model.creatures.swamp.WanderingBaldMan;
import com.kevinquan.cwa.model.spells.BoneWand;
import com.kevinquan.cwa.model.spells.BriefPower;
import com.kevinquan.cwa.model.spells.BubblegumButt;
import com.kevinquan.cwa.model.spells.CerebralBloodstorm;
import com.kevinquan.cwa.model.spells.ClairvoyantDaggerstorm;
import com.kevinquan.cwa.model.spells.CornScepter;
import com.kevinquan.cwa.model.spells.CrystalBall;
import com.kevinquan.cwa.model.spells.DoorOfStrength;
import com.kevinquan.cwa.model.spells.FieldOfNightmares;
import com.kevinquan.cwa.model.spells.FountainOfForgiveness;
import com.kevinquan.cwa.model.spells.HotDogRain;
import com.kevinquan.cwa.model.spells.PieStorm;
import com.kevinquan.cwa.model.spells.PortalToNowhere;
import com.kevinquan.cwa.model.spells.PumaClaw;
import com.kevinquan.cwa.model.spells.ScrollOfBadBreath;
import com.kevinquan.cwa.model.spells.ScrollOfFreshBreath;
import com.kevinquan.cwa.model.spells.SnakeEyeRing;
import com.kevinquan.cwa.model.spells.StrawberryButt;
import com.kevinquan.cwa.model.spells.SuperHug;
import com.kevinquan.cwa.model.spells.ThroneOfDoom;
import com.kevinquan.cwa.model.spells.TomeOfAnkhs;
import com.kevinquan.cwa.model.spells.UltimateMagicHands;
import com.kevinquan.cwa.model.spells.UnemptyCoffin;
import com.kevinquan.cwa.model.spells.Volcano;
import com.kevinquan.cwa.model.spells.WitchWay;
import com.kevinquan.cwa.model.spells.WizardMigrane;
import com.kevinquan.cwa.model.spells.WoadBlood;


public class LootDropStore {
    
    public static class LootDropPriorityComparator implements Comparator<LootDropDetails> {

        @Override
        public int compare(LootDropDetails arg0, LootDropDetails arg1) {
            // Static weight
            if (arg0.getStaticWeight() != arg1.getStaticWeight()) {
                // Higher first
                return arg0.getStaticWeight() - arg1.getStaticWeight() > 0 ? -1 : 1;
            }
            Card lhs = arg0.getCard();
            Card rhs = arg1.getCard();
            // Rarity
            if (lhs.getRarity().getStars() != rhs.getRarity().getStars()) {
                // Rarer first
                return lhs.getRarity().getStars() - rhs.getRarity().getStars() > 0 ? -1 : 1;
            }
            // Alphabetical
            return lhs.getName().compareToIgnoreCase(rhs.getName());
        }
        
    }
    
    public static class LootDropDetails {
        
        protected Level mLevel;
        protected Card mCard;
        protected double mDropChance;
        protected double mStaticWeight;
        
        public LootDropDetails(Card card, Level level, double chance, double weight) {
            mCard = card;
            mLevel = level;
            mDropChance = chance;
            mStaticWeight = weight;
        }

        public Level getLevel() {
            return mLevel;
        }

        public Card getCard() {
            return mCard;
        }
        
        public double getDropChance() {
            return mDropChance;
        }

        public double getStaticWeight() {
            return mStaticWeight;
        }
    }

    @SuppressWarnings("unused")
    private static final String TAG = LootDropStore.class.getSimpleName();
    
    private static class LootDropStoreHolder {
        private static final LootDropStore INSTANCE = new LootDropStore();
    }
    
    public static LootDropStore getInstance() {
        return LootDropStoreHolder.INSTANCE;
    }
    
    protected Hashtable<String, List<LootDropDetails>> mCardIndex;
    protected Hashtable<Integer, List<LootDropDetails>> mLevelIndex;
    
    private LootDropStore() {
        mCardIndex = new Hashtable<String, List<LootDropDetails>>();
        mLevelIndex = new Hashtable<Integer, List<LootDropDetails>>();
        init();
    }
    
    protected void addDropDetails(LootDropDetails details) {
        Card card = details.getCard();
        if (!mCardIndex.containsKey(card.getId())) {
            List<LootDropDetails> drops = new ArrayList<LootDropDetails>();
            mCardIndex.put(card.getId(), drops);
        }
        mCardIndex.get(card.getId()).add(details);
        int levelNumber = details.getLevel().getLevelNumber();
        if (!mLevelIndex.containsKey(levelNumber)) {
            List<LootDropDetails> drops = new ArrayList<LootDropDetails>();
            mLevelIndex.put(levelNumber, drops);
        }
        mLevelIndex.get(levelNumber).add(details);
    }
    
    public List<LootDropDetails> getDropsFor(Card card) {
        List<LootDropDetails> result = new ArrayList<LootDropDetails>();
        if (card != null && mCardIndex.containsKey(card.getId())) {
            result.addAll(mCardIndex.get(card.getId()));
        }
        return result;
    }
    
    public List<LootDropDetails> getDropsFor(int levelNumber) {
        List<LootDropDetails> result = new ArrayList<LootDropDetails>();
        if (levelNumber > 0 && levelNumber < Level.MAXIMUM_LEVEL && mLevelIndex.containsKey(levelNumber)) {
            result.addAll(mLevelIndex.get(levelNumber));
        }
        return result;        
    }
    
    protected void init() {
        LevelStore levelStore = LevelStore.getInstance();
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(1), 0.0, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(2), 0.0, 100.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(3), 1.0, 100.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(3), 1.0, 100.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(3), 1.0, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(4), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(4), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Cornball(), levelStore.getLevel(4), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new GrapeSlimey(), levelStore.getLevel(4), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(4), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(4), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(4), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(5), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(5), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CrystalBall(), levelStore.getLevel(5), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new EthanAllfire(), levelStore.getLevel(5), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(5), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(5), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(5), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Cornball(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new EthanAllfire(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new GrapeSlimey(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(6), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(7), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(7), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new OrangeSlimey(), levelStore.getLevel(7), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(7), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(7), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WanderingBaldMan(), levelStore.getLevel(7), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(7), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(8), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(8), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new OrangeSlimey(), levelStore.getLevel(8), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(8), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(8), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WanderingBaldMan(), levelStore.getLevel(8), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(8), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(9), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new OrangeSlimey(), levelStore.getLevel(9), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(9), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WanderingBaldMan(), levelStore.getLevel(9), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(9), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(10), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(10), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(10), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Fluffapillar(), levelStore.getLevel(10), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(10), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(10), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(10), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(11), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(11), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(11), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Fluffapillar(), levelStore.getLevel(11), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(11), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(11), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(11), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(12), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(12), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Fluffapillar(), levelStore.getLevel(12), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(12), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(12), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(12), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new BurningHand(), levelStore.getLevel(13), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(13), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(13), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CrystalBall(), levelStore.getLevel(13), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new GreenCactaball(), levelStore.getLevel(13), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(13), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(13), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(13), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new BurningHand(), levelStore.getLevel(14), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(14), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CrystalBall(), levelStore.getLevel(14), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new GreenCactaball(), levelStore.getLevel(14), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(14), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(14), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(14), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new BurningHand(), levelStore.getLevel(15), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(15), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new CrystalBall(), levelStore.getLevel(15), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new GreenCactaball(), levelStore.getLevel(15), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(15), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(15), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(15), 0.5, 500.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(16), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(16), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(16), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(16), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(17), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(17), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(17), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new GreenCactaball(), levelStore.getLevel(17), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(17), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(17), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BeachMum(), levelStore.getLevel(17), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(18), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(18), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HuskerWorm(), levelStore.getLevel(18), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new SoftEyeling(), levelStore.getLevel(18), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(18), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(18), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FatGoat(), levelStore.getLevel(18), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(19), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(19), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(19), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(19), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TeethLeaf(), levelStore.getLevel(19), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(19), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(19), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(19), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(20), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(20), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(20), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(20), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(20), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(20), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(20), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BeachMum(), levelStore.getLevel(20), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(21), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(21), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(21), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(21), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(21), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(21), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(21), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(21), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(22), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new MsMummy(), levelStore.getLevel(22), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new OrangeSlimey(), levelStore.getLevel(22), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TeethLeaf(), levelStore.getLevel(22), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(22), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BoneWand(), levelStore.getLevel(22), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(22), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(23), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new OrangeSlimey(), levelStore.getLevel(23), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TeethLeaf(), levelStore.getLevel(23), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(23), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BoneWand(), levelStore.getLevel(23), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(23), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(24), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new OrangeSlimey(), levelStore.getLevel(24), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TeethLeaf(), levelStore.getLevel(24), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(24), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BoneWand(), levelStore.getLevel(24), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(24), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(25), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new EthanAllfire(), levelStore.getLevel(25), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new GreenCactaball(), levelStore.getLevel(25), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new MsMummy(), levelStore.getLevel(25), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(25), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(25), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TomeOfAnkhs(), levelStore.getLevel(25), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(26), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new GreenCactaball(), levelStore.getLevel(26), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new MsMummy(), levelStore.getLevel(26), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new SoftEyeling(), levelStore.getLevel(26), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(26), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(26), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TomeOfAnkhs(), levelStore.getLevel(26), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(27), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new GreenCactaball(), levelStore.getLevel(27), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new MsMummy(), levelStore.getLevel(27), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(27), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TeethLeaf(), levelStore.getLevel(27), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(27), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TomeOfAnkhs(), levelStore.getLevel(27), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(28), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(28), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Cornball(), levelStore.getLevel(28), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(28), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(28), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornScepter(), levelStore.getLevel(28), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new PumaClaw(), levelStore.getLevel(28), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(29), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(29), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Cornball(), levelStore.getLevel(29), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(29), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(29), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(29), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BoneWand(), levelStore.getLevel(29), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(30), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Cornball(), levelStore.getLevel(30), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Fluffapillar(), levelStore.getLevel(30), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(30), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(30), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BoneWand(), levelStore.getLevel(30), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new SuperHug(), levelStore.getLevel(30), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new FatGoat(), levelStore.getLevel(30), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(31), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(31), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(31), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(31), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(31), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(31), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PumaClaw(), levelStore.getLevel(31), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(31), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(32), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(32), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(32), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new MsMummy(), levelStore.getLevel(32), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(32), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(32), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PumaClaw(), levelStore.getLevel(32), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(32), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(33), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(33), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(33), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(33), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(33), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(33), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PumaClaw(), levelStore.getLevel(33), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(33), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(34), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(34), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(34), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(34), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(34), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(34), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(35), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(35), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(35), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(35), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(35), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(35), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(36), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(36), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(36), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(36), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(36), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(36), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(37), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(37), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Fluffapillar(), levelStore.getLevel(37), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new SoftEyeling(), levelStore.getLevel(37), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ScrollOfFreshBreath(), levelStore.getLevel(37), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(37), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(38), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(38), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TeethLeaf(), levelStore.getLevel(38), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ScrollOfFreshBreath(), levelStore.getLevel(38), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(38), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(39), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BurningHand(), levelStore.getLevel(39), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(39), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BeachMum(), levelStore.getLevel(39), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ScrollOfFreshBreath(), levelStore.getLevel(39), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(39), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(40), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HuskerWorm(), levelStore.getLevel(40), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(40), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(40), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornScepter(), levelStore.getLevel(40), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new HuskerWorm(), levelStore.getLevel(41), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(41), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornScepter(), levelStore.getLevel(41), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(42), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(42), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HuskerWorm(), levelStore.getLevel(42), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new SoftEyeling(), levelStore.getLevel(42), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(42), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(42), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(42), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(43), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(43), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(43), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TomeOfAnkhs(), levelStore.getLevel(43), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(43), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new BurningHand(), levelStore.getLevel(44), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Cornball(), levelStore.getLevel(44), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(44), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornScepter(), levelStore.getLevel(44), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(44), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(44), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(44), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new BurningHand(), levelStore.getLevel(45), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(45), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TeethLeaf(), levelStore.getLevel(45), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornScepter(), levelStore.getLevel(45), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(45), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(45), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(45), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(46), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(46), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FieldOfNightmares(), levelStore.getLevel(46), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new WitchWay(), levelStore.getLevel(46), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CornParthenon(), levelStore.getLevel(46), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(46), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(47), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(47), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FieldOfNightmares(), levelStore.getLevel(47), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new WitchWay(), levelStore.getLevel(47), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CornParthenon(), levelStore.getLevel(47), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(47), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(48), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(48), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FieldOfNightmares(), levelStore.getLevel(48), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new WitchWay(), levelStore.getLevel(48), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CornParthenon(), levelStore.getLevel(48), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(48), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new BurningHand(), levelStore.getLevel(49), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(49), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(49), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(49), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BeachMum(), levelStore.getLevel(49), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new PumaClaw(), levelStore.getLevel(49), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(49), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(50), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(50), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(50), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TeethLeaf(), levelStore.getLevel(50), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PumaClaw(), levelStore.getLevel(50), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(50), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(51), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CoolDog(), levelStore.getLevel(51), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HeavenlyGazer(), levelStore.getLevel(51), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(51), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PumaClaw(), levelStore.getLevel(51), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(51), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new HuskerWorm(), levelStore.getLevel(52), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(52), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(52), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BoneWand(), levelStore.getLevel(52), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new HotDogRain(), levelStore.getLevel(52), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(53), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(53), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BoneWand(), levelStore.getLevel(53), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new HotDogRain(), levelStore.getLevel(53), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(54), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TeethLeaf(), levelStore.getLevel(54), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(54), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BoneWand(), levelStore.getLevel(54), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(55), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(55), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(55), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(55), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(56), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(56), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(56), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(57), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(57), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(57), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new AngelHeart(), levelStore.getLevel(58), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(58), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(58), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FatGoat(), levelStore.getLevel(58), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(58), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new SnakeEyeRing(), levelStore.getLevel(58), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(58), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(59), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(59), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new SnakeEyeRing(), levelStore.getLevel(59), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(59), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(59), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(60), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new TomeOfAnkhs(), levelStore.getLevel(60), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(60), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new SnakeEyeRing(), levelStore.getLevel(60), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(60), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(60), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(61), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(61), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(61), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(61), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(61), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(62), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(62), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(62), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(62), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(63), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(63), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(63), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(63), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(64), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HuskerWorm(), levelStore.getLevel(64), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(64), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(64), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FatGoat(), levelStore.getLevel(64), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new SnakeEyeRing(), levelStore.getLevel(64), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(64), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new HuskerWorm(), levelStore.getLevel(65), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(65), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(65), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(65), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new SnakeEyeRing(), levelStore.getLevel(65), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(66), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new HuskerWorm(), levelStore.getLevel(66), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(66), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(66), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new SnakeEyeRing(), levelStore.getLevel(66), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(67), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new GrapeSlimey(), levelStore.getLevel(67), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(67), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(67), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThroneOfDoom(), levelStore.getLevel(67), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(68), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(68), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(68), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(68), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThroneOfDoom(), levelStore.getLevel(68), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(68), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(69), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(69), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(69), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(69), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(69), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(69), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new ThroneOfDoom(), levelStore.getLevel(69), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(69), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(70), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(70), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(70), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(70), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(70), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(70), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(71), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(71), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(71), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(71), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(71), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(72), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(72), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(72), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(73), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(73), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PortalToNowhere(), levelStore.getLevel(73), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(73), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new ScrollOfBadBreath(), levelStore.getLevel(73), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(73), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(74), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(74), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(74), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PortalToNowhere(), levelStore.getLevel(74), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(74), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new ScrollOfBadBreath(), levelStore.getLevel(74), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(74), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(74), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(75), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(75), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(75), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(75), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PortalToNowhere(), levelStore.getLevel(75), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(75), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new ScrollOfBadBreath(), levelStore.getLevel(75), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(75), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new WhiteNinja(), levelStore.getLevel(75), 0.37, 1.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(76), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(76), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(76), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(76), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BriefPower(), levelStore.getLevel(76), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(76), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(76), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(76), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(77), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(77), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(77), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new BriefPower(), levelStore.getLevel(77), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(77), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(77), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(77), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(78), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(78), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(78), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(78), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(78), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(78), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(79), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(79), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(79), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(79), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(79), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(80), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Mouthball(), levelStore.getLevel(80), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(80), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(80), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(80), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(81), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(81), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(81), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(81), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(81), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(82), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(82), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(82), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(83), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(83), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(83), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(83), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(83), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(84), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(84), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(84), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(84), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(85), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(85), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(85), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(85), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(85), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(85), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(86), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(86), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(86), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(86), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(86), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(86), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(86), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(87), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(87), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(87), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(87), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(87), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(87), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(88), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(88), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(88), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(88), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(88), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(89), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(89), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(89), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(89), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(89), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(90), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ThePig(), levelStore.getLevel(90), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(90), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(90), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(90), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(90), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(90), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(91), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(91), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(91), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(91), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(91), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(91), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new ThroneOfDoom(), levelStore.getLevel(91), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(91), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(92), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(92), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(92), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(92), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(92), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(92), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new ThroneOfDoom(), levelStore.getLevel(92), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(92), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(93), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(93), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(93), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(93), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(93), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(93), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new ThroneOfDoom(), levelStore.getLevel(93), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(93), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(94), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(94), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(94), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ScrollOfFreshBreath(), levelStore.getLevel(94), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CornParthenon(), levelStore.getLevel(94), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(94), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(94), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(94), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ScrollOfBadBreath(), levelStore.getLevel(94), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(95), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(95), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(95), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ScrollOfFreshBreath(), levelStore.getLevel(95), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CornParthenon(), levelStore.getLevel(95), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(95), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(95), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(95), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ScrollOfBadBreath(), levelStore.getLevel(95), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(96), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(96), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(96), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FatGoat(), levelStore.getLevel(96), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ScrollOfFreshBreath(), levelStore.getLevel(96), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new CornParthenon(), levelStore.getLevel(96), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(96), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(96), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(96), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ScrollOfBadBreath(), levelStore.getLevel(96), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(97), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(97), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(97), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BeachMum(), levelStore.getLevel(97), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(97), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(97), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(97), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(97), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(97), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(98), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(98), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(98), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(98), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(98), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(98), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(98), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(98), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(99), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(99), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(99), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(99), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(99), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(99), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(99), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(99), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(100), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(100), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(100), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(100), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(100), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(100), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(101), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(101), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(101), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(101), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(101), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(101), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(102), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(102), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(102), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(102), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(102), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(102), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(103), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(103), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(103), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(103), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(103), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(103), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(104), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(104), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(104), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(104), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(104), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(104), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(105), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(105), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(105), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(105), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(105), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(105), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(106), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(106), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(106), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(106), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(106), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(106), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(106), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(106), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(106), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(107), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(107), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(107), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(107), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(107), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(107), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(107), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(107), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(107), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(108), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(108), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(108), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(108), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(108), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(108), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(108), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(108), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(108), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(109), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(109), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(109), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(109), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(109), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new FieldOfNightmares(), levelStore.getLevel(109), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(109), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(109), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(110), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(110), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(110), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(110), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(110), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new FieldOfNightmares(), levelStore.getLevel(110), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(110), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(110), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(111), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(111), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(111), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new BubblegumButt(), levelStore.getLevel(111), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(111), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new FieldOfNightmares(), levelStore.getLevel(111), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(111), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UltimateMagicHands(), levelStore.getLevel(111), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(112), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(112), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(112), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(112), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(112), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(112), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ThroneOfDoom(), levelStore.getLevel(112), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new BriefPower(), levelStore.getLevel(112), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(112), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(112), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldAngelHeart(), levelStore.getLevel(112), 0.37, 5.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(112), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(113), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(113), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(113), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(113), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(113), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(113), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ThroneOfDoom(), levelStore.getLevel(113), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new BriefPower(), levelStore.getLevel(113), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(113), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(113), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldAngelHeart(), levelStore.getLevel(113), 0.37, 5.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(113), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(114), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new CornDome(), levelStore.getLevel(114), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(114), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(114), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(114), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(114), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new ThroneOfDoom(), levelStore.getLevel(114), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new BriefPower(), levelStore.getLevel(114), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(114), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new SchoolHouse(), levelStore.getLevel(114), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldAngelHeart(), levelStore.getLevel(114), 0.37, 5.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(114), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(115), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(115), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(115), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(115), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CornParthenon(), levelStore.getLevel(115), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(115), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(115), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new BriefPower(), levelStore.getLevel(115), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(115), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ScrollOfBadBreath(), levelStore.getLevel(115), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(116), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(116), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(116), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(116), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CornParthenon(), levelStore.getLevel(116), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(116), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(116), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new BriefPower(), levelStore.getLevel(116), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(116), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ScrollOfBadBreath(), levelStore.getLevel(116), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(116), 0.37, 4.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(117), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(117), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(117), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(117), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new CornParthenon(), levelStore.getLevel(117), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new PieStorm(), levelStore.getLevel(117), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(117), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new BriefPower(), levelStore.getLevel(117), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(117), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new ScrollOfBadBreath(), levelStore.getLevel(117), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(118), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(118), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(118), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(118), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(118), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(118), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(118), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(118), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(118), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new CerebralBloodstorm(), levelStore.getLevel(119), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new StrawberryButt(), levelStore.getLevel(119), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new Volcano(), levelStore.getLevel(119), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WizardMigrane(), levelStore.getLevel(119), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new WoadBlood(), levelStore.getLevel(119), 0.37, 500.0));
        addDropDetails(new LootDropDetails(new FountainOfForgiveness(), levelStore.getLevel(119), 0.37, 400.0));
        addDropDetails(new LootDropDetails(new ClairvoyantDaggerstorm(), levelStore.getLevel(119), 0.37, 300.0));
        addDropDetails(new LootDropDetails(new UnemptyCoffin(), levelStore.getLevel(119), 0.37, 200.0));
        addDropDetails(new LootDropDetails(new DoorOfStrength(), levelStore.getLevel(119), 0.37, 100.0));
        addDropDetails(new LootDropDetails(new GoldFatGoat(), levelStore.getLevel(119), 0.37, 4.0));
    }

}
